CREATE TABLE Organizer (
	id INT NOT NULL AUTO_INCREMENT,
	name VARCHAR(50) NOT NULL,
	created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (id)
);

CREATE TABLE venue (
	id INT NOT NULL AUTO_INCREMENT,
	created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	streetAddress1 VARCHAR(40),
	streetAddress2 VARCHAR(40),
	city VARCHAR(20),
	state VARCHAR(20),
	country VARCHAR(20),
	pincode VARCHAR(10),
	PRIMARY KEY (id)
);

CREATE TABLE EVENT (
	id INT NOT NULL AUTO_INCREMENT,
	name VARCHAR(50) NOT NULL,
	created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	starttime TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	endtime TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	status BOOL DEFAULT FALSE,
	organizer_id INT NOT NULL,
	venue_id INT,
	PRIMARY KEY (id),
	FOREIGN KEY (organizer_id) REFERENCES organizer(id) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY (venue_id) REFERENCES venue(id) ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE TABLE participant (
	id INT NOT NULL AUTO_INCREMENT,
	email VARCHAR(50) NOT NULL,
	created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	event_id INT,
	PRIMARY KEY (id),
	FOREIGN KEY (event_id) REFERENCES event(id) ON DELETE SET NULL ON UPDATE CASCADE,
	UNIQUE (email, event_id)
);